version: '3'

services:

  db:
    image: mysql:5.7
    restart: 'always'
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./docker/mysql/slave/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./docker/mysql:/var/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socnet
      MYSQL_USER: usr
      MYSQL_PASSWORD: usr

volumes:
  mysql_volume:
