version: '3'

services:

  app:
    build:
      context: docker/php
    restart: 'no'
    environment:
      PHP_IDE_CONFIG: "remote_host=172.26.0.1"
      XDEBUG_CONFIG: "serverName=socnet"
    volumes:
      - ./:/var/www/app:cached

  nginx:
    build:
      context: docker/nginx
    restart: 'no'
    links:
      - app
    ports:
      - 80:80
      - 443:443

  db-master:
    image: mysql:5.7
    restart: 'no'
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql:cached
      - ./docker/mysql/master/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./docker/mysql:/var/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socnet
      MYSQL_USER: usr
      MYSQL_PASSWORD: usr

  db-slave:
    image: mysql:5.7
    restart: 'no'
    ports:
      - 3307:3306
    links:
      - db-master
    volumes:
      - mysql_slave:/var/lib/mysql:cached
      - ./docker/mysql/slave/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./docker/mysql:/var/data
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socnet
      MYSQL_USER: usr
      MYSQL_PASSWORD: usr

volumes:
  mysql_volume:
  mysql_slave:
