version: '3'

services:

  app:
    build:
      context: docker/php
    restart: 'always'
    links:
      - db
    volumes:
      - ./:/var/www/app

  nginx:
    build:
      context: docker/nginx
    restart: 'always'
    links:
      - app
    ports:
      - 80:80
    volumes:
      - ./:/var/www/app

  db:
    image: mysql:5.7
    restart: 'always'
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socnet
      MYSQL_USER: usr
      MYSQL_PASSWORD: usr

volumes:
  mysql_volume:
