version: '3'

services:

  app:
    build:
      context: docker/php
    restart: 'no'
    environment:
      PHP_IDE_CONFIG: "remote_host=172.26.0.1"
      XDEBUG_CONFIG: "serverName=socnet"
    volumes:
      - ./:/var/www/app:cached

  nginx:
    build:
      context: docker/nginx
    restart: 'no'
    links:
      - app
    ports:
      - 80:80
      - 443:443

  db:
    image: mysql:5.7
    restart: 'no'
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socnet
      MYSQL_USER: usr
      MYSQL_PASSWORD: usr

volumes:
  mysql_volume:
